<a href="https://colab.research.google.com/github/Giihgallicchio/Programacao-em-Python-Data-Science/blob/main/2%C2%BA_M%C3%A3o_na_Massa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel('Planilhas/Report-consolidado (3).xlsx')
df.head()

,Segmento,País,Produto,Qtde de Unidades Vendidas,Preço Unitário,Valor Total,Desconto,Valor Total c/ Desconto,Custo Total,Lucro,Data,Mês,Ano
0,Governo,Alemanha,Produto 1,1321.0,20,26420.0,0.0,26420.0,14531.0,11889.0,2019-01-01,Janeiro,2019
1,Governo,Alemanha,Produto 1,1513.0,350,529550.0,0.0,529550.0,432718.0,96832.0,2019-12-01,Dezembro,2019
2,Governo,Alemanha,Produto 2,2146.0,7,15022.0,0.0,15022.0,10730.0,4292.0,2019-09-01,Setembro,2019
3,Governo,Alemanha,Produto 3,1006.0,350,352100.0,0.0,352100.0,261560.0,90540.0,2019-06-01,Junho,2019
4,Governo,Alemanha,Produto 3,1513.0,350,529550.0,0.0,529550.0,393380.0,136170.0,2019-12-01,Dezembro,2019

In [ ]:
df.dtypes

Segmento                             object
País                                 object
Produto                              object
Qtde de Unidades Vendidas           float64
Preço Unitário                        int64
Valor Total                         float64
Desconto                            float64
Valor Total c/ Desconto             float64
Custo Total                         float64
Lucro                               float64
Data                         datetime64[ns]
Mês                                  object
Ano                                   int64
dtype: object

In [ ]:
df.duplicated().sum()

700

In [ ]:
df.describe()

,Qtde de Unidades Vendidas,Preço Unitário,Valor Total,Desconto,Valor Total c/ Desconto,Custo Total,Lucro,Data,Ano
count,1400.000000,1400.000000,1.400000e+03,1400.000000,1.400000e+03,1400.000000,1400.000000,1400,1400.000000
mean,1608.294286,118.428571,1.827594e+05,13150.354629,1.696091e+05,147187.854714,22421.217086,2019-04-28 21:36:00,2018.750000
min,200.000000,7.000000,1.799000e+03,0.000000,1.655080e+03,918.000000,-71250.250000,2018-09-01 00:00:00,2018.000000
25%,905.000000,12.000000,1.739175e+04,800.320000,1.592800e+04,7538.000000,2701.800000,2018-12-24 06:00:00,2018.750000
50%,1542.500000,20.000000,3.798000e+04,2585.250000,3.554020e+04,22580.000000,8936.400000,2019-05-16 12:00:00,2019.000000
75%,2229.125000,300.000000,2.790250e+05,15956.343750,2.610775e+05,248422.500000,21155.745000,2019-09-08 12:00:00,2019.000000
max,4492.500000,350.000000,1.207500e+06,149677.500000,1.159200e+06,950625.000000,262200.000000,2019-12-01 00:00:00,2019.000000
std,867.117787,136.726623,2.541714e+05,22954.720400,2.366417e+05,205856.427873,42267.614060,NaN,0.433167

In [ ]:
df.isnull().sum()

Segmento                     0
País                         0
Produto                      0
Qtde de Unidades Vendidas    0
Preço Unitário               0
Valor Total                  0
Desconto                     0
Valor Total c/ Desconto      0
Custo Total                  0
Lucro                        0
Data                         0
Mês                          0
Ano                          0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1400 entries, 0 to 1399
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Segmento                   1400 non-null   object
 1   País                       1400 non-null   object
 2   Produto                    1400 non-null   object
 3   Qtde de Unidades Vendidas  1400 non-null   float64
 4   Preço Unitário             1400 non-null   int64
 5   Valor Total                1400 non-null   float64
 6   Desconto                   1400 non-null   float64
 7   Valor Total c/ Desconto    1400 non-null   float64
 8   Custo Total                1400 non-null   float64
 9   Lucro                      1400 non-null   float64
 10  Data                       1400 non-null   datetime64[ns]
 11  Mês                        1400 non-null   object
 12  Ano                        1400 non-null   int64
dtypes: datetime64[ns](1), float64(6), int64(2), object(4)
memory usage: 142.3+ KB

In [ ]:
df = df_ordenado = df.sort_values(by='Lucro',ascending=True)
df_ordenado

,Segmento,País,Produto,Qtde de Unidades Vendidas,Preço Unitário,Valor Total,Desconto,Valor Total c/ Desconto,Custo Total,Lucro,Data,Mês,Ano
316,Grandes empresas,Alemanha,Produto 1,2767.0,125,345875.0,51881.25,293993.75,365244.0,-71250.25,2019-08-01,Agosto,2019
1016,Grandes empresas,Alemanha,Produto 1,2767.0,125,345875.0,51881.25,293993.75,365244.0,-71250.25,2019-08-01,Agosto,2019
358,Grandes empresas,Chile,Produto 1,2821.0,125,352625.0,49367.50,303257.50,372372.0,-69114.50,2018-12-01,Dezembro,2018
1058,Grandes empresas,Chile,Produto 1,2821.0,125,352625.0,49367.50,303257.50,372372.0,-69114.50,2018-12-01,Dezembro,2018
373,Grandes empresas,EUA,Produto 1,3445.5,125,430687.5,43068.75,387618.75,454806.0,-67187.25,2019-04-01,Abril,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...
711,Governo,Alemanha,Produto 6,2966.0,350,1038100.0,20762.00,1017338.00,771160.0,246178.00,2018-10-01,Outubro,2018
242,Governo,França,Produto 6,2750.0,350,962500.0,0.00,962500.00,715000.0,247500.00,2019-02-01,Fevereiro,2019
942,Governo,França,Produto 6,2750.0,350,962500.0,0.00,962500.00,715000.0,247500.00,2019-02-01,Fevereiro,2019
891,Governo,EUA,Produto 3,3450.0,350,1207500.0,48300.00,1159200.00,897000.0,262200.00,2019-07-01,Julho,2019
191,Governo,EUA,Produto 3,3450.0,350,1207500.0,48300.00,1159200.00,897000.0,262200.00,2019-07-01,Julho,2019

In [ ]:
df_ordenado.groupby(['Segmento', 'País', 'Ano'])[['Lucro']].min().reset_index().sort_values(by='Lucro', ascending=True) #Lucro Negativo

             Segmento      País   Ano     Lucro
11   Grandes empresas  Alemanha  2019 -71250.25
14   Grandes empresas     Chile  2018 -69114.50
17   Grandes empresas       EUA  2019 -67187.25
12   Grandes empresas    Canadá  2018 -53152.00
19   Grandes empresas    França  2019 -50650.75
15   Grandes empresas     Chile  2019 -47432.00
16   Grandes empresas       EUA  2018 -33522.50
18   Grandes empresas    França  2018 -28899.00
33  Pequenas empresas    Canadá  2019 -25432.00
31  Pequenas empresas  Alemanha  2019 -22488.00
13   Grandes empresas    Canadá  2019 -18967.50
37  Pequenas empresas       EUA  2019 -17170.00
35  Pequenas empresas     Chile  2019 -13617.00
10   Grandes empresas  Alemanha  2018 -12861.50
1             Governo  Alemanha  2019    145.60
6             Governo       EUA  2018    284.04
9             Governo    França  2019    298.86
3             Governo    Canadá  2019    370.08
5             Governo     Chile  2019    453.27
7             Governo       EUA  2019    655.50
21    Médias empresas  Alemanha  2019    806.20
25    Médias empresas     Chile  2019    894.25
23    Médias empresas    Canadá  2019    959.20
0             Governo  Alemanha  2018   1168.40
24    Médias empresas     Chile  2018   1216.00
29    Médias empresas    França  2019   1372.00
8             Governo    França  2018   1556.81
28    Médias empresas    França  2018   1556.85
4             Governo     Chile  2018   1761.54
39  Pequenas empresas    França  2019   1792.00
20    Médias empresas  Alemanha  2018   2013.00
32  Pequenas empresas    Canadá  2018   2152.00
27    Médias empresas       EUA  2019   2166.40
2             Governo    Canadá  2018   2207.07
48      Vendas online    França  2018   2423.52
44      Vendas online     Chile  2018   2796.54
46      Vendas online       EUA  2018   2895.00
26    Médias empresas       EUA  2018   2952.40
45      Vendas online     Chile  2019   3050.40
41      Vendas online  Alemanha  2019   3303.00
22    Médias empresas    Canadá  2018   3666.00
30  Pequenas empresas  Alemanha  2018   4066.00
43      Vendas online    Canadá  2019   4807.92
40      Vendas online  Alemanha  2018   6572.28
47      Vendas online       EUA  2019   6580.80
49      Vendas online    França  2019   7378.32
38  Pequenas empresas    França  2018   7406.00
42      Vendas online    Canadá  2018   7572.72
34  Pequenas empresas     Chile  2018  10868.00
36  Pequenas empresas       EUA  2018  12870.00

In [ ]:
df_ordenado.groupby(['Segmento', 'País', 'Ano'])[['Lucro']].min().reset_index().sort_values(by='Lucro', ascending=False) #Lucro Positivo

             Segmento      País   Ano     Lucro
36  Pequenas empresas       EUA  2018  12870.00
34  Pequenas empresas     Chile  2018  10868.00
42      Vendas online    Canadá  2018   7572.72
38  Pequenas empresas    França  2018   7406.00
49      Vendas online    França  2019   7378.32
47      Vendas online       EUA  2019   6580.80
40      Vendas online  Alemanha  2018   6572.28
43      Vendas online    Canadá  2019   4807.92
30  Pequenas empresas  Alemanha  2018   4066.00
22    Médias empresas    Canadá  2018   3666.00
41      Vendas online  Alemanha  2019   3303.00
45      Vendas online     Chile  2019   3050.40
26    Médias empresas       EUA  2018   2952.40
46      Vendas online       EUA  2018   2895.00
44      Vendas online     Chile  2018   2796.54
48      Vendas online    França  2018   2423.52
2             Governo    Canadá  2018   2207.07
27    Médias empresas       EUA  2019   2166.40
32  Pequenas empresas    Canadá  2018   2152.00
20    Médias empresas  Alemanha  2018   2013.00
39  Pequenas empresas    França  2019   1792.00
4             Governo     Chile  2018   1761.54
28    Médias empresas    França  2018   1556.85
8             Governo    França  2018   1556.81
29    Médias empresas    França  2019   1372.00
24    Médias empresas     Chile  2018   1216.00
0             Governo  Alemanha  2018   1168.40
23    Médias empresas    Canadá  2019    959.20
25    Médias empresas     Chile  2019    894.25
21    Médias empresas  Alemanha  2019    806.20
7             Governo       EUA  2019    655.50
5             Governo     Chile  2019    453.27
3             Governo    Canadá  2019    370.08
9             Governo    França  2019    298.86
6             Governo       EUA  2018    284.04
1             Governo  Alemanha  2019    145.60
10   Grandes empresas  Alemanha  2018 -12861.50
35  Pequenas empresas     Chile  2019 -13617.00
37  Pequenas empresas       EUA  2019 -17170.00
13   Grandes empresas    Canadá  2019 -18967.50
31  Pequenas empresas  Alemanha  2019 -22488.00
33  Pequenas empresas    Canadá  2019 -25432.00
18   Grandes empresas    França  2018 -28899.00
16   Grandes empresas       EUA  2018 -33522.50
15   Grandes empresas     Chile  2019 -47432.00
19   Grandes empresas    França  2019 -50650.75
12   Grandes empresas    Canadá  2018 -53152.00
17   Grandes empresas       EUA  2019 -67187.25
14   Grandes empresas     Chile  2018 -69114.50
11   Grandes empresas  Alemanha  2019 -71250.25

In [ ]:
df_ordenado.dtypes

Segmento                             object
País                                 object
Produto                              object
Qtde de Unidades Vendidas           float64
Preço Unitário                        int64
Valor Total                         float64
Desconto                            float64
Valor Total c/ Desconto             float64
Custo Total                         float64
Lucro                               float64
Data                         datetime64[ns]
Mês                                  object
Ano                                   int64
dtype: object