<a href="https://colab.research.google.com/github/Giihgallicchio/Programacao-em-Python-Data-Science/blob/main/Carregando_Dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Biblioteca do Pandas
O **Pandas** é uma biblioteca para manipulação, análise e visualição de dados.
Foi desenvolvida com base no **Numpy** e **Matplotilib**.

pip install Pandas

**Site oficial:** https://pandas.pydata.org/

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [ ]:
# Carregando dados com Pandas
import pandas as pd
import sqlite3

In [ ]:
# CSV delimitador - vírgula
df = pd.read_csv('DataSets/base_vendas.csv')

In [ ]:
#head Tráz as primeiras 5 linhas do arquivo
df.head()

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,NaN,28/09/2020 16:19,05/10/2020 16:31
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,NaN,07/03/2020 12:47,08/03/2020 12:47
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,NaN,21/04/2019 10:48,23/04/2019 15:55
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,"899,9","1676,9",1,NaN,07/05/2020 17:59,08/05/2020 14:31
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",14/08/2019 16:56,19/08/2019 15:52

In [ ]:
#tail tráz as últimas 5 linhas do arquivo
df.tail()

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
2995,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10006,Aspirador de pó,Casa,"88,9","189,9",3,NaN,04/11/2019 15:40,05/11/2019 10:40
2996,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10011,Liquidificador,Cozinha,"59,9","142,4",3,NaN,24/06/2019 09:04,24/06/2019 10:50
2997,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,"49,9","95,9",3,NaN,08/08/2020 14:46,09/08/2020 14:07
2998,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10010,Fritadeira elétrica,Cozinha,"187,9",340,3,NaN,19/12/2019 09:21,19/12/2019 10:51
2999,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",3,"0,09",18/03/2019 15:40,23/03/2019 17:52

In [ ]:
#head Tráz as primeiras 20 linhas do arquivo
df.head(20)

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,NaN,28/09/2020 16:19,05/10/2020 16:31
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,NaN,07/03/2020 12:47,08/03/2020 12:47
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,NaN,21/04/2019 10:48,23/04/2019 15:55
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,"899,9","1676,9",1,NaN,07/05/2020 17:59,08/05/2020 14:31
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",14/08/2019 16:56,19/08/2019 15:52
5,123456111,José Maria,Vendedor,CL001,Loja Matriz,10010,Fritadeira elétrica,Cozinha,"187,9",340,1,NaN,10/07/2019 15:11,11/07/2019 14:30
6,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,NaN,26/06/2019 11:03,28/06/2019 13:37
7,123456111,José Maria,Vendedor,CL001,Loja Matriz,10006,Aspirador de pó,Casa,"88,9","189,9",1,NaN,15/03/2020 13:00,16/03/2020 11:15
8,123456111,José Maria,Vendedor,CL001,Loja Matriz,10010,Fritadeira elétrica,Cozinha,"187,9",340,1,NaN,15/08/2020 11:36,15/08/2020 14:22
9,123456111,José Maria,Vendedor,CL001,Loja Matriz,10017,Cama Box,Casa,"1189,9","1899,5",1,NaN,06/03/2019 13:01,11/03/2019 12:01
10,123456111,José Maria,Vendedor,CL001,Loja Matriz,10003,Televisão,Eletrodomésticos,"1400,9","2279,99",1,NaN,11/10/2019 12:44,17/10/2019 14:58
11,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",30/10/2019 17:22,03/11/2019 10:21
12,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,NaN,28/05/2020 16:00,29/05/2020 14:16
13,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,NaN,30/12/2019 15:07,04/01/2020 16:48
14,123456111,José Maria,Vendedor,CL001,Loja Matriz,10016,Guarda Roupa,Casa,"489,9",999,1,NaN,16/04/2019 09:22,23/04/2019 10:49
15,123456111,José Maria,Vendedor,CL001,Loja Matriz,10020,Impressora,Eletrônicos,"329,9","674,1",1,NaN,07/09/2019 15:29,08/09/2019 13:00
16,123456111,José Maria,Vendedor,CL001,Loja Matriz,10017,Cama Box,Casa,"1189,9","1899,5",1,NaN,18/03/2019 09:08,25/03/2019 15:58
17,123456111,José Maria,Vendedor,CL001,Loja Matriz,10008,Cafeteira,Cozinha,"159,9","284,9",1,NaN,28/01/2020 16:40,29/01/2020 11:59
18,123456111,José Maria,Vendedor,CL001,Loja Matriz,10015,Microondas,Eletrodomésticos,189,"364,5",1,NaN,30/10/2020 17:27,31/10/2020 14:16
19,123456111,José Maria,Vendedor,CL001,Loja Matriz,10016,Guarda Roupa,Casa,"489,9",999,1,NaN,23/10/2020 17:41,30/10/2020 09:27

In [ ]:
#tail tráz as últimas 20 linhas do arquivo
df.tail(20)

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
2980,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10003,Televisão,Eletrodomésticos,"1400,9","2279,99",3,NaN,21/09/2020 17:15,28/09/2020 12:17
2981,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",3,NaN,05/07/2020 13:17,11/07/2020 16:14
2982,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10001,Smartphone,Eletrônicos,"899,9","1676,9",3,NaN,05/03/2019 16:00,06/03/2019 15:21
2983,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10009,Ferro de passar,Casa,"27,9","55,9",3,NaN,18/03/2019 16:40,19/03/2019 16:03
2984,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10005,Notebook,Eletrônicos,"2299,9",3199,3,NaN,29/03/2020 12:34,29/03/2020 14:49
2985,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",3,"0,09",10/05/2019 17:16,17/05/2019 12:42
2986,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10012,Processador de alimentos,Cozinha,110,"189,9",3,NaN,24/01/2020 11:16,24/01/2020 16:20
2987,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10002,Tablet,Eletrônicos,799,"1424,91",3,NaN,06/03/2019 11:01,06/03/2019 17:29
2988,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10011,Liquidificador,Cozinha,"59,9","142,4",3,NaN,05/05/2020 15:56,06/05/2020 15:20
2989,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10002,Tablet,Eletrônicos,799,"1424,91",3,NaN,26/05/2020 14:53,27/05/2020 11:01
2990,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",3,NaN,04/12/2020 13:24,10/12/2020 11:05
2991,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10016,Guarda Roupa,Casa,"489,9",999,3,NaN,13/06/2020 16:58,15/06/2020 17:41
2992,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10010,Fritadeira elétrica,Cozinha,"187,9",340,3,NaN,02/07/2019 16:56,03/07/2019 09:27
2993,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10001,Smartphone,Eletrônicos,"899,9","1676,9",3,NaN,18/12/2019 17:59,19/12/2019 16:33
2994,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10001,Smartphone,Eletrônicos,"899,9","1676,9",3,NaN,26/01/2019 16:06,26/01/2019 16:16
2995,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10006,Aspirador de pó,Casa,"88,9","189,9",3,NaN,04/11/2019 15:40,05/11/2019 10:40
2996,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10011,Liquidificador,Cozinha,"59,9","142,4",3,NaN,24/06/2019 09:04,24/06/2019 10:50
2997,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10007,Batedeira,Cozinha,"49,9","95,9",3,NaN,08/08/2020 14:46,09/08/2020 14:07
2998,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10010,Fritadeira elétrica,Cozinha,"187,9",340,3,NaN,19/12/2019 09:21,19/12/2019 10:51
2999,123457113,Victor Hugo,Vendedor,CL004,Filial ES,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",3,"0,09",18/03/2019 15:40,23/03/2019 17:52

In [ ]:
# Arquivo CSV delimitador - ponto e vírgula ; (sep é um separador)
df = pd.read_csv('DataSets/base_vendas_ponto_virgula.csv', sep=';')
df.head()

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,NaN,28/09/2020 16:19,05/10/2020 16:31
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,NaN,07/03/2020 12:47,08/03/2020 12:47
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,NaN,21/04/2019 10:48,23/04/2019 15:55
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,"899,9","1676,9",1,NaN,07/05/2020 17:59,08/05/2020 14:31
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",14/08/2019 16:56,19/08/2019 15:52

In [ ]:
# CSV delimitador - \t (\t = arquivo com tab/espaço separando cada informação) delimiter é igual o sep (utilizado para separar)
df = pd.read_csv('DataSets/base_vendas_tab.tsv', delimiter='\t')
df.head()

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,NaN,28/09/2020 16:19,05/10/2020 16:31
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,NaN,07/03/2020 12:47,08/03/2020 12:47
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,NaN,21/04/2019 10:48,23/04/2019 15:55
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,"899,9","1676,9",1,NaN,07/05/2020 17:59,08/05/2020 14:31
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",14/08/2019 16:56,19/08/2019 15:52

In [ ]:
# Arquivos Excel - pip install openpyxl (sheet_name especifica o nome da planilha para ser utilizada)
df =pd.read_excel('DataSets/Vendas.xlsx', sheet_name='base_vendas')
df.head()

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,210.9,404.1,1,NaN,2020-09-28 16:19:00,2020-10-05 16:31:00
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,109.9,249.9,1,NaN,2020-03-07 12:47:00,2020-03-08 12:47:00
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,699.9,1346.9,1,NaN,2019-04-21 10:48:00,2019-04-23 15:55:00
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,899.9,1676.9,1,NaN,2020-05-07 17:59:00,2020-05-08 14:31:00
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099.0,1709.1,1,0.05,2019-08-14 16:56:00,2019-08-19 15:52:00

In [ ]:
# Arquivo HTML
tabelas = pd.read_html('DataSets/base_vendas.html')

In [ ]:
len(tabelas)

1

In [ ]:
df = tabelas[0]

In [ ]:
df.head()

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,2109,4041,1,NaN,28/09/2020 16:19,05/10/2020 16:31
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,1099,2499,1,NaN,07/03/2020 12:47,08/03/2020 12:47
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,6999,13469,1,NaN,21/04/2019 10:48,23/04/2019 15:55
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,8999,16769,1,NaN,07/05/2020 17:59,08/05/2020 14:31
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,17091,1,5.0,14/08/2019 16:56,19/08/2019 15:52

In [ ]:
# Arquivo HDFS - Área Cientifica
df = pd.read_hdf('DataSets/base_vendas.h5')
df.head()

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,NaN,28/09/2020 16:19,05/10/2020 16:31
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,NaN,07/03/2020 12:47,08/03/2020 12:47
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,NaN,21/04/2019 10:48,23/04/2019 15:55
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,"899,9","1676,9",1,NaN,07/05/2020 17:59,08/05/2020 14:31
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",14/08/2019 16:56,19/08/2019 15:52

In [ ]:
#Mostra quantas linhas e colunas tem no arquivo
df.shape

(100, 14)

In [ ]:
#Informações do arquivo
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 0 to 99
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   matricula_funcionario  100 non-null    int64
 1   Nome Funcionario       100 non-null    object
 2   Cargo                  100 non-null    object
 3   codigo_loja            100 non-null    object
 4   nome_loja              100 non-null    object
 5   codigo_produto         100 non-null    int64
 6   descricao_produto      100 non-null    object
 7   Categoria              100 non-null    object
 8   preco_custo            100 non-null    object
 9   valor_unitario         100 non-null    object
 10  quantidade             100 non-null    int64
 11  comissao               9 non-null      object
 12  dt_venda               100 non-null    object
 13  dt_entrega             100 non-null    object
dtypes: int64(3), object(11)
memory usage: 15.8+ KB

In [ ]:
#Descrição
df.describe()

       matricula_funcionario  codigo_produto  quantidade
count                  100.0      100.000000   100.00000
mean             123456111.0    10010.810000     1.42000
std                      0.0        6.043103     0.81872
min              123456111.0    10001.000000     1.00000
25%              123456111.0    10004.750000     1.00000
50%              123456111.0    10012.000000     1.00000
75%              123456111.0    10016.000000     1.00000
max              123456111.0    10020.000000     3.00000

In [ ]:
# Arquivos de Banco de Dados -SQLite3
conn = sqlite3.connect('DataSets/vendas.db')
df = pd.read_sql_query('Select descricao_produto, count(*) as Qtde \
                       From pedidos Group By descricao_produto \
                       Order By count(*) desc ', conn)
df.head()

     descricao_produto  Qtde
0  Máquina Lavar Roupa     9
1           Smartphone     7
2           Microondas     7
3         Guarda Roupa     7
4            Geladeira     7

In [ ]:
df = pd.read_xml('DataSets/base_vendas.xml')
df.head()

,index,matricula_funcionario,nome_funcionario,cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,None,28/09/2020 16:19,05/10/2020 16:31
1,1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,None,07/03/2020 12:47,08/03/2020 12:47
2,2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,None,21/04/2019 10:48,23/04/2019 15:55
3,3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,"899,9","1676,9",1,None,07/05/2020 17:59,08/05/2020 14:31
4,4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",14/08/2019 16:56,19/08/2019 15:52

In [ ]:
df = pd.read_json('DataSets/base_vendas.json')
df.head()

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,None,28/09/2020 16:19,05/10/2020 16:31
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,None,07/03/2020 12:47,08/03/2020 12:47
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,None,21/04/2019 10:48,23/04/2019 15:55
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,"899,9","1676,9",1,None,07/05/2020 17:59,08/05/2020 14:31
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",14/08/2019 16:56,19/08/2019 15:52