<a href="https://colab.research.google.com/github/Giihgallicchio/Programacao-em-Python-Data-Science/blob/main/DataPrep_Duplicados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Preparação de Dados (Data Prep)
### Tratando Dados Duplicados

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame(
    {
        'Aluno': ['João', 'Maria', 'Helena', 'Joel', 'Gabriel'],
        'Idade': [30,25,18,29,45]
    }
)
df

     Aluno  Idade
0     João     30
1    Maria     25
2   Helena     18
3     Joel     29
4  Gabriel     45

In [ ]:
#Mostra na onde esta duplicado
df.duplicated()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [ ]:
#Tras a quantidade de duplicidade
df.duplicated().sum()
#tambem pode mostrar uma coluna em especifico a quatindade de duplicidade
df['Aluno'].duplicated().sum()

np.int64(0)

In [ ]:
#Duplicando as informações
df_dup = pd.concat( (df, df) )
#ordenando o nome do aluno
df_dup.sort_values(by='Aluno')

     Aluno  Idade
4  Gabriel     45
4  Gabriel     45
2   Helena     18
2   Helena     18
3     Joel     29
3     Joel     29
0     João     30
0     João     30
1    Maria     25
1    Maria     25

In [ ]:
df_dup.duplicated().sum()

np.int64(5)

In [ ]:
df_dup['Aluno'].duplicated().sum()

np.int64(5)

In [ ]:
#exclui a duplicidade
df_unicos = df_dup.drop_duplicates()
df_unicos

     Aluno  Idade
0     João     30
1    Maria     25
2   Helena     18
3     Joel     29
4  Gabriel     45

In [ ]:
df.duplicated().sum()

np.int64(0)